services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # Puerto para conexiones AMQP
      - "15672:15672"  # Interfaz web de gestión

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./imagenes:/app/imagenes  # Carpeta compartida
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    volumes:
      - ./imagenes:/app/imagenes
    depends_on:
      - rabbitmq
      - server